FROM registry.xpaas.lenovo.com/library/postgres:9.6.2-alpine


ENV POSTGRES_DB netdevops
ENV POSTGRES_USER i_netdevops
ENV POSTGRES_PASSWORD localdb
ENV PGDATA /home/lib/postgresql/data/pgdata

EXPOSE 5432
