version: '3'
services:  
  db: 
    image: registry.xpaas.lenovo.com/library/postgres:9.6.2-alpine
    ports:
     - 5432:5432
    environment:
      - POSTGRES_DB=netdevops
      - POSTGRES_USER=i_netdevops
      - POSTGRES_PASSWORD=localdb
      - PGDATA=/home/lib/postgresql/data/pgdata

