apiVersion: v1
kind: ReplicationController
metadata:
  name: fronted
spec:
  replicas: 3
  selector: 
    app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: pho-redis
        image: wangyanglinux/myapp:v1
        env:
        - name: GET_HOSTS_FROM
          value: dns
          name: zhangsan
          value: "123"
        ports:
        - containerPort: 80